spring:
 application:
   name: chatservice
 datasource:
  initialization-mode: always    
 jpa:
   hibernate:
    ddl-auto: update 
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true