spring:
 application:
   name: generalbankingservice
 datasource:
  initialization-mode: always  
 jpa:
   hibernate:
    ddl-auto: update
server:
  port: 9195  
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true 
     