server:
 port: 9193
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bucketList?createDatabaseIfNotExist=true
      username: root
      password: 
      driver-classs-name: com.mysql.jdbc.Driver     
   jpa:
     hibernate:
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none   