server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
         uri: https://bitbucket.org/Ranu_00/paymob-cloud-config-store-3
         search-paths: 
          - '*service'
  application:
    name: paymob-service-config
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true    