server:
 port: 9192
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/chatmessage?createDatabaseIfNotExist=true
      username: root
      password: 
      driver-classs-name: com.mysql.jdbc.Driver     
   jpa:
     hibernate:
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
whatsapp:
   firstmessage: Please select 1) Transfer money 2) Create Bucket List 3) offer & Loan 