server:
 port: 9197
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/chatmessage?createDatabaseIfNotExist=true
      username: root
      password: Micro@123
      driver-classs-name: com.mysql.jdbc.Driver
      data: classpath:insert_chat_category_script.sql
   jpa:
     hibernate:
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
whatsapp:
   firstmessage: Please select 1) Transfer money 2) Create Bucket List 3) offer & Loan 